runtime: python310

instance_class: F2

env_variables:
  ROBOFLOW_API_KEY: "xxxxxxxxxxxxxxxxxxxxxxxx"

entrypoint: gunicorn -b :$PORT main:app --workers 2 --threads 4 --timeout 0

handlers:
- url: /.*
  script: auto
  secure: always


